# boot.ini — AthenaStudio (visual editor)

[tick]
ms=50

[boot]
slides=1
handoff=after_slide
es6=true

[splash.0]
background=#202020
holdms=1000
text.0=Built with Athena2ME
textx.0=%W2%
texty.0=%H2%
textsize.0=MEDIUM
textcolor.0=#ffffff
textalign.0=center
text.1=A modern JavaScript runtime for J2ME
textx.1=%W2%
texty.1=%H2%+20
textsize.1=SMALL
textcolor.1=#8000ff
textalign.1=center
text.2=Loading...
textx.2=8
texty.2=8
textsize.2=SMALL
textcolor.2=#cccccc
textalign.2=left
image.0=
imagex.0=0
imagey.0=40
